import type { AttackPointDef } from '../types'

export const ATTACK_POINTS: AttackPointDef[] = [
  {
    // Single PC hotspot. Opens the upgraded Windows desktop; the 5 PC sub-attacks
    // (phish, CEO fraud, fake Chrome update, LinkedIn attachment, fake Defender) unfold inside it
    // and are scored by pcStore, which banks the total on this point via completePoint(1).
    id: 1, displayName: 'Main Workstation', label: 'PC Workstation', tag: 'ATK_PC',
    anchorKey: 'PC_MONITOR_1', camKey: 'pc',
    triggerOS: 'windows', appToOpen: null, audioCue: 'ui_click', scoreReward: 550,
    isAttack: true, normalContext: null,
    briefing: "Your workstation has been active since morning. Several things need your attention — check your email, browser downloads, and any files that arrive.",
    hint: "Not every threat announces itself. Look carefully at sender addresses, reply-to fields, download domains, file extensions, and process parents.",
    time: '15:52',
    contextIcon: '🖥',
    contextHeader: 'YOUR WORKSTATION',
    contextNarrative: "You sit down at your main workstation. Outlook is open. There are a few unread emails. The browser is running in the background. Everything looks normal. But something is already waiting for you.",
    actionLabel: 'Start Working',
    contextAudioCue: 'ui_click',
  },
  {
    id: 4, displayName: 'Personal Phone', label: 'SMS Phishing', tag: 'ATK_004',
    anchorKey: 'MOBILE_DESK', camKey: 'phone',
    triggerOS: 'android', appToOpen: 'messages', audioCue: 'sms_notification', scoreReward: 120,
    isAttack: true, normalContext: null,
    briefing: "You received a text from a bank shortcode. Does anything seem off?",
    hint: "Shortened links can hide the real destination. Expand it and compare the final domain to your bank's real domain.",
    time: '16:08',
    contextIcon: '📱',
    contextHeader: 'TEXT MESSAGE',
    contextNarrative: "Your personal phone buzzed. A text from shortcode 7726 claims to be National Bank, warns about a blocked payment, and pushes you to verify through a shortened link.",
    actionLabel: 'Read Message',
    contextAudioCue: 'sms_notification',
  },
  {
    id: 5, displayName: 'Office Landline', label: 'Vishing Call', tag: 'ATK_005',
    anchorKey: 'DESK_PHONE', camKey: 'landline',
    triggerOS: 'android', appToOpen: 'dialer', audioCue: 'phone_ring_landline', scoreReward: 120,
    isAttack: false, normalContext: "A caller ID claims to be from IT support.",
    briefing: "Phone call incoming. The caller ID says IT Helpdesk, but the caller wants remote access and tells you not to call back through official channels.",
    hint: "A spoofed caller ID is not proof. Would your real IT team pressure you not to verify the request independently?",
    time: '16:15',
    contextIcon: '📞',
    contextHeader: 'INCOMING CALL',
    contextNarrative: "The office landline is ringing. The display shows: IT Helpdesk — Internal Ext 4471. A calm voice says your machine is infected, needs remote access right now, and warns you not to hang up or call the official help desk queue.",
    actionLabel: 'Answer Call',
    contextAudioCue: 'phone_ring_landline',
  },
  {
    id: 6, displayName: 'Unknown USB / Finance PC', label: 'USB Bait', tag: 'ATK_006',
    anchorKey: 'WASHROOM', camKey: 'usb',
    triggerOS: 'windows', appToOpen: 'fileExplorer', audioCue: 'ui_click', scoreReward: 150,
    isAttack: true, normalContext: null,
    briefing: "You found a USB stick in the washroom labelled 'Salary 2025'. Curiosity is the vulnerability.",
    hint: "You didn't buy this USB. You don't know where it's been. What would happen if you opened those files?",
    time: '16:21',
    contextIcon: '🔌',
    contextHeader: 'UNKNOWN DEVICE FOUND',
    contextNarrative: "On your way back from the bathroom you spotted a USB stick on the counter with a printed label: 'HR_PAYROLL_Q4 — CONFIDENTIAL'. Nobody is around. You pick it up.",
    actionLabel: 'Plug It In',
    actionLabelSecondary: 'Leave It & Report',
    secondaryIsCorrect: true,
    contextAudioCue: 'usb_insert',
  },
  {
    id: 7, displayName: 'Office Door', label: 'Delivery Pretext', tag: 'ATK_007',
    anchorKey: 'ENTRY_DOOR', camKey: 'door',
    triggerOS: 'scene', appToOpen: null, audioCue: 'door_knock', scoreReward: 150,
    isAttack: false, normalContext: "A delivery arrived at the front door.",
    briefing: "Unexpected delivery. The courier has an unusual request after you sign. What do you do?",
    hint: "What legitimate reason would a delivery person have to access your server room?",
    time: '16:28',
    // ATK_007 keeps its bespoke DeliveryCard — no generic context card fields.
  },
  {
    id: 8, displayName: 'Admin Workstation', label: 'Malware Detection', tag: 'ATK_008',
    anchorKey: 'NOTEPAD', camKey: 'notepad',
    triggerOS: 'windows', appToOpen: 'fileExplorer', audioCue: 'ui_click', scoreReward: 200,
    isAttack: true, normalContext: null,
    briefing: "An unknown process is running on your PC. The USB from earlier may have been a trap.",
    hint: "The goal isn't to fix it yourself — it's to contain the damage.",
    time: '16:34',
    contextIcon: '⚠',
    contextHeader: 'SYSTEM ANOMALY',
    contextNarrative: "Back at your workstation, Task Manager shows svch0st.exe — with a zero — running from a temp folder under wscript.exe. It started 4 minutes ago. You remember the USB from earlier.",
    actionLabel: 'Investigate Process',
    contextAudioCue: 'system_alert',
  },
]
