import type { AttackPointDef } from '../types'

export const ATTACK_POINTS: AttackPointDef[] = [
  {
    id: 1, displayName: 'Main Workstation', label: 'Phishing Email', tag: 'ATK_001',
    anchorKey: 'PC_MONITOR_1', camKey: 'pc',
    triggerOS: 'windows', appToOpen: 'outlook', audioCue: 'ui_click', scoreReward: 100,
    isAttack: true, normalContext: null,
    briefing: "A suspicious email arrived in your Outlook inbox. Something about the sender is wrong.",
    hint: "Look very carefully at the sender's email address. Every character matters.",
    time: '15:52',
    contextIcon: '📧',
    contextHeader: 'NEW EMAIL',
    contextNarrative: "A new message landed in your Outlook inbox while you were making tea. The subject line says URGENT. The sender claims to be IT Support. Something feels slightly off before you've even opened it.",
    actionLabel: 'Open Outlook',
    contextAudioCue: 'email_notification',
  },
  {
    id: 2, displayName: "John's Workstation", label: 'Fake Chrome Update', tag: 'ATK_002',
    anchorKey: 'PC_MONITOR_2', camKey: 'pc',
    triggerOS: 'windows', appToOpen: 'browser', audioCue: 'ui_click', scoreReward: 100,
    isAttack: true, normalContext: null,
    briefing: "Your browser has a popup demanding an update. Is it legitimate?",
    hint: "Where does the download actually come from? Check the URL carefully.",
    time: '15:57',
    contextIcon: '🌐',
    contextHeader: 'BROWSER ALERT',
    contextNarrative: "You walked past John's workstation. His screen is covered by a browser popup demanding an immediate security update. John isn't at his desk. The popup is still waiting for a click.",
    actionLabel: 'Investigate',
    contextAudioCue: 'ui_click',
  },
  {
    id: 3, displayName: 'Designer PC', label: 'LinkedIn Scam', tag: 'ATK_003',
    anchorKey: 'PC_MONITOR_3', camKey: 'pc',
    triggerOS: 'windows', appToOpen: 'browser', audioCue: 'ui_click', scoreReward: 100,
    isAttack: false, normalContext: "A LinkedIn recruiter sent a connection request.",
    briefing: "You have a new LinkedIn message with an attachment. Not everything is what it seems.",
    hint: "Look very carefully at the file extension. What comes after .pdf?",
    time: '16:03',
    contextIcon: '🔗',
    contextHeader: 'LINKEDIN MESSAGE',
    contextNarrative: "A recruiter named 'Sarah' connected with you on LinkedIn two days ago. She just sent a follow-up message with an attachment — a PDF with job opportunities. The file name looks normal at first glance.",
    actionLabel: 'View Message',
    contextAudioCue: 'email_notification',
  },
  {
    id: 4, displayName: 'Personal Phone', label: 'SMS Phishing', tag: 'ATK_004',
    anchorKey: 'MOBILE_DESK', camKey: 'phone',
    triggerOS: 'android', appToOpen: 'messages', audioCue: 'sms_notification', scoreReward: 120,
    isAttack: true, normalContext: null,
    briefing: "You received a text from your bank. Does anything seem off?",
    hint: "What's the actual web address in the message? Compare it to your bank's real domain.",
    time: '16:08',
    contextIcon: '📱',
    contextHeader: 'TEXT MESSAGE',
    contextNarrative: "Your personal phone buzzed. A text from what appears to be your bank — National Bank — warning about suspicious activity on your account and urging you to verify immediately via a link.",
    actionLabel: 'Read Message',
    contextAudioCue: 'sms_notification',
  },
  {
    id: 5, displayName: 'Office Landline', label: 'Vishing Call', tag: 'ATK_005',
    anchorKey: 'DESK_PHONE', camKey: 'landline',
    triggerOS: 'android', appToOpen: 'dialer', audioCue: 'phone_ring_landline', scoreReward: 120,
    isAttack: false, normalContext: "A caller claims to be from IT support.",
    briefing: "Phone call incoming. IT support wants to help remotely. Should you trust them?",
    hint: "Would your real IT team need YOU to do anything on your computer to help you?",
    time: '16:15',
    contextIcon: '📞',
    contextHeader: 'INCOMING CALL',
    contextNarrative: "The office landline is ringing. The display shows: IT Support — Internal. A calm male voice says he has detected unusual activity on your machine and needs remote access to fix it right now.",
    actionLabel: 'Answer Call',
    contextAudioCue: 'phone_ring_landline',
  },
  {
    id: 6, displayName: 'Unknown USB / Finance PC', label: 'USB Bait', tag: 'ATK_006',
    anchorKey: 'WASHROOM', camKey: 'usb',
    triggerOS: 'windows', appToOpen: 'fileExplorer', audioCue: 'ui_click', scoreReward: 150,
    isAttack: true, normalContext: null,
    briefing: "You found a USB stick in the washroom labelled 'Salary 2025'. Curiosity is the vulnerability.",
    hint: "You didn't buy this USB. You don't know where it's been. What would happen if you opened those files?",
    time: '16:21',
    contextIcon: '🔌',
    contextHeader: 'UNKNOWN DEVICE FOUND',
    contextNarrative: "On your way back from the bathroom you spotted something on the counter — a USB stick with a handwritten label: 'SALARY REVIEW 2025 — CONFIDENTIAL'. Nobody is around. You pick it up.",
    actionLabel: 'Plug It In',
    actionLabelSecondary: 'Leave It & Report',
    secondaryIsCorrect: true,
    contextAudioCue: 'usb_insert',
  },
  {
    id: 7, displayName: 'Office Door', label: 'Delivery Pretext', tag: 'ATK_007',
    anchorKey: 'ENTRY_DOOR', camKey: 'door',
    triggerOS: 'scene', appToOpen: null, audioCue: 'door_knock', scoreReward: 150,
    isAttack: false, normalContext: "A delivery arrived at the front door.",
    briefing: "Unexpected delivery. The courier has an unusual request after you sign. What do you do?",
    hint: "What legitimate reason would a delivery person have to access your server room?",
    time: '16:28',
    // ATK_007 keeps its bespoke DeliveryCard — no generic context card fields.
  },
  {
    id: 8, displayName: 'Admin Workstation', label: 'Malware Detection', tag: 'ATK_008',
    anchorKey: 'NOTEPAD', camKey: 'notepad',
    triggerOS: 'windows', appToOpen: 'fileExplorer', audioCue: 'ui_click', scoreReward: 200,
    isAttack: true, normalContext: null,
    briefing: "An unknown process is running on your PC. The USB from earlier may have been a trap.",
    hint: "The goal isn't to fix it yourself — it's to contain the damage.",
    time: '16:34',
    contextIcon: '⚠',
    contextHeader: 'SYSTEM ANOMALY',
    contextNarrative: "Back at your workstation, Task Manager shows an unfamiliar process — svchost32.exe — consuming 87% CPU from a temp folder. It started 4 minutes ago. You remember the USB from earlier.",
    actionLabel: 'Investigate Process',
    contextAudioCue: 'system_alert',
  },
]
