// Provisions an employee: creates a Supabase auth user (role=employee) so a
// profiles row is generated by the handle_new_user trigger. Runs with the
// service-role key (server-side only). The caller must be an authenticated
// super_admin or org_admin; org_admins can only create within their own org.
import { createClient } from 'jsr:@supabase/supabase-js@2';

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...cors, 'Content-Type': 'application/json' },
  });
}

function tempPassword(): string {
  const bytes = crypto.getRandomValues(new Uint8Array(18));
  const b64 = btoa(String.fromCharCode(...bytes)).replace(/[+/=]/g, '');
  // Ensure it satisfies common complexity rules.
  return `Aa1!${b64}`.slice(0, 20);
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });
  if (req.method !== 'POST') return json({ error: 'Method not allowed' }, 405);

  const url = Deno.env.get('SUPABASE_URL');
  const anonKey = Deno.env.get('SUPABASE_ANON_KEY');
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  if (!url || !anonKey || !serviceKey) {
    return json({ error: 'Server misconfigured' }, 500);
  }

  const authHeader = req.headers.get('Authorization');
  if (!authHeader) return json({ error: 'Missing authorization' }, 401);

  // Identify the caller with their own JWT (RLS-enforced).
  const caller = createClient(url, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await caller.auth.getUser();
  if (userErr || !userData.user) return json({ error: 'Invalid session' }, 401);

  const { data: callerProfile, error: profErr } = await caller
    .from('profiles')
    .select('role, org_id')
    .eq('id', userData.user.id)
    .single();
  if (profErr || !callerProfile) return json({ error: 'Profile not found' }, 403);
  if (callerProfile.role !== 'super_admin' && callerProfile.role !== 'org_admin') {
    return json({ error: 'Not authorized to create employees' }, 403);
  }

  let body: {
    name?: string;
    email?: string;
    orgId?: string;
    jobRole?: string;
    age?: number;
    gender?: string;
  };
  try {
    body = await req.json();
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  const name = (body.name ?? '').trim();
  const email = (body.email ?? '').trim();
  if (!name || !email) return json({ error: 'name and email are required' }, 400);

  // org_admins are pinned to their own org; super_admins must name one.
  const orgId = callerProfile.role === 'org_admin' ? callerProfile.org_id : body.orgId;
  if (!orgId) return json({ error: 'orgId is required' }, 400);

  const admin = createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const password = tempPassword();
  const { data: created, error: createErr } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { full_name: name, role: 'employee', org_id: orgId },
  });
  if (createErr || !created.user) {
    return json({ error: createErr?.message ?? 'Could not create user' }, 400);
  }

  // handle_new_user created the profile; fill the extra fields it doesn't read.
  const { error: updateErr } = await admin
    .from('profiles')
    .update({
      job_role: body.jobRole ?? null,
      age: body.age ?? null,
      gender: body.gender ?? null,
    })
    .eq('id', created.user.id);
  if (updateErr) {
    return json({ error: updateErr.message }, 400);
  }

  return json({ id: created.user.id, email, password });
});
